### ISSUE TITLE
Exception on boot, Sponge #449

### ISSUE THREAD

**Issue by JoeSchmo2840** [mmonkey/Destinations#3] opened 2015-05-23 04:09 UTC
http://pastebin.com/2iGn3DJ4

**Comment by mmonkey** [comment] 2015-05-27 14:50
This exception is caused by a change in Sponge API, however there isn't an official 2.1 release of the API yet. I was planning on waiting for the official update to fix this exception. If you go back a few versions, then everything works.

**Comment by JoeSchmo2840** [comment] 2015-05-28 07:12
Okay, Im planning on running a dedicated test server and honestly Im not running it until I can show off what I consider one of its greatest features. Pagination is absolutely incredible. And there arent any /home systems yet. But if I run pre 449 then 50% of the other plugins break. I really appreciate your work and hope to see an update soon :D

**Comment by mmonkey** [comment] 2015-06-26 04:43
Fixed in v0.0.3-2.1

**Closed as completed by mmonkey** 2015-06-26 04:43 UTC
